DevLab_PostoAmigo/Controllers/EventoController.cs
using DevLab_PostoAmigo.Business.Util;
using DevLab_PostoAmigo.Business.Return;
using DevLab_PostoAmigo.Data;
using DevLab_PostoAmigo.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.IO;

namespace DevLab_PostoAmigo.Controllers
{
    public class EventoController : Controller
    {
        [SessionCheck]
        public ActionResult Index()
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();
            ViewBag.IdStatus = new SelectList(Business.StatusEvent.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");

            var model = new Models.EventModel();
            model.ListEvent = Business.Event.ListEvent(null, null);

            return View(model);
        }

        [SessionCheck]
        [HttpGet]
        public ActionResult Index(int? id)
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();
            ViewBag.IdStatus = new SelectList(Business.StatusEvent.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text", id.ToString());

            var model = new Models.EventModel();
            model.ListEvent = Business.Event.ListEvent(null, id);

            return View(model);
        }

        [SessionCheck]
        [HttpPost]
        public ActionResult Filtrar(Models.EventModel model)
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();
            ViewBag.IdStatus = new SelectList(Business.StatusEvent.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");

            model.ListEvent = Business.Event.ListEvent(model.Ibm, model.IdStatus);

            return View("Index", model);
        }

        [SessionCheck]
        [HttpGet]
        public ActionResult Export(long? Ibm, int? IdStatus)
        {
            ViewBag.IdStatus = new SelectList(Business.StatusEvent.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");

            var eventos = Business.Event.ListEvent(Ibm, IdStatus);
            // Create file
            DateTime now = TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("Central Brazilian Standard Time"));
            string filename = "Relatorio_Eventos_" + now.ToString("ddMMyyyyHHmm") + ".xlsx";

            // Criar excel
            MemoryStream stream = new MemoryStream();
            ExcelStructure excel = new ExcelStructure("Eventos", ref stream);

            excel.setColumnWidth(1, 20);  // Ibm
            excel.setColumnWidth(2, 20);  // NameStatus
            excel.setColumnWidth(3, 20);  // Name
            excel.setColumnWidth(4, 30);  // Description
            excel.setColumnWidth(5, 20);  // DateEvent
            excel.setColumnWidth(6, 20);  // HourStart
            excel.setColumnWidth(7, 20);  // HourEnd
            excel.setColumnWidth(8, 20);  // Comments
            excel.setColumnWidth(9, 20);  // Reason
            excel.setColumnWidth(10, 20); // DateCreate
            excel.setColumnWidth(11, 20); // DateUpdate

            excel.createSheetData();

            IList<string> headers = new List<string>();
            IList<string> valores = new List<string>();
            IList<int> tipos = new List<int>();

            headers = new List<string>();

            headers.Add("Ibm");
            headers.Add("Status");
            headers.Add("Titulo");
            headers.Add("Descrição");
            headers.Add("Data Evento");
            headers.Add("Hora Inicio");
            headers.Add("Hora Termino");
            headers.Add("Observações");
            headers.Add("Motivo");
            headers.Add("Data Criação");
            headers.Add("Data Atualização");

            excel.CreateColumnHeader(1, headers);

            uint row = 2;
            foreach (var c in eventos)
            {
                valores = new List<string>();
                tipos = new List<int>();

                valores.Add(c.Ibm + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.NameStatus + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Name + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Description + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.DateEvent + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.HourStart + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.HourEnd + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Comments + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Reason + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.DateCreate + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.DateUpdate + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                excel.CreateRowWithContent(row, valores, tipos);
                row++;
            }

            excel.save();
            excel.close();

            stream.Position = 0;

            return new FileStreamResult(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            {
                FileDownloadName = filename
            };
        }

        [SessionCheck]
        public ActionResult Details(int id)
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();

            var statusEvent = Business.StatusEvent.ListStatus();

            Event eventt = Business.Event.Details(id);
            Models.EventModel model = new Models.EventModel
            {
                IdEvent = eventt.IdEvent,
                Ibm = eventt.Ibm,
                IdStatus = eventt.IdStatus,
                Name = eventt.Name,
                Description = eventt.Description,
                Comments = eventt.Comments,
                DateEvent = eventt.DateEvent,
                HourStart = eventt.HourStart,
                HourEnd = eventt.HourEnd,
                Reason = eventt.Reason,
                DateCreate = eventt.DateCreate,
                DateUpdate = eventt.DateUpdate,
                NameStatus = eventt.NameStatus,
                ListStatusEvent = statusEvent
            };

            return View(model);
        }

        [SessionCheck]
        [HttpPost]
        public ActionResult Edit(string strDados)
        {
            Models.EventModel dados;

            try
            {
                dados = JsonConvert.DeserializeObject<Models.EventModel>(strDados);

                Business.Event.Edit(dados.IdEvent, (int)dados.IdStatus, dados.Name, dados.Description, dados.Comments, dados.Reason);
            }
            catch
            {

            }

            return Json(true);
        }
    }
}

DevLab_PostoAmigo/Views/Evento/Details.cshtml
@model DevLab_PostoAmigo.Models.EventModel

<div class="content-wrapper full-wide">
    <!-- Content Header (Page header) -->
    @*<section class="content-header">
            <h1>Dashboard</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
            </ol>
        </section>*@

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="chart-box">
                    <div class="row">
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>IBM</label>
                                <input class="form-control" id="basicInput" type="text" value="@Model.Ibm" readonly="readonly">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Titulo do evento</label>
                                <input class="form-control" id="txtName" type="text" value="@Model.Name">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Data do evento</label>
                                <input class="form-control" id="basicInput" type="text" value="@Model.DateEvent.ToString("dd/MM/yyyy")" readonly="readonly">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Hora início</label>
                                <input class="form-control" id="basicInput" type="text" value="@Model.HourStart" readonly="readonly">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Hora término</label>
                                <input class="form-control" id="basicInput" type="text" value="@Model.HourEnd" readonly="readonly">
                            </fieldset>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Descrição do evento</label>
                                <textarea class="form-control" id="txtDescription" rows="10">@Model.Description</textarea>
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Observações adicionais sobre o evento</label>
                                <textarea class="form-control" id="txtComments" rows="10">@Model.Comments</textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Status</label>
                                <select class="form-control" id="IdStatus">
                                    @foreach (var item in Model.ListStatusEvent)
                                    {
                                        if (item.IdStatus == Model.IdStatus)
                                        {
                                            <option value="@item.IdStatus" selected>@item.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@item.IdStatus">@item.Name</option>
                                        }
                                    }
                                </select>
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group" id="dvReason">
                                <label>Motivo</label>
                                <textarea class="form-control" id="txtReason" rows="10">@Model.Reason</textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <input type="hidden" value="@Model.IdEvent" id="IdEvento" />
                            <a href="#" id="btnVoltar" class="btn btn-warning btn-rounded">Voltar</a>
                            <a href="#" id="btnSalvar" class="btn btn-info btn-rounded">Salvar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- content -->
</div>
<!-- content-wrapper -->
<!-- content-wrapper -->

@section scripts {
    <!-- Custom -->
    <script src="~/Scripts/dist/js/EventDetails.js"></script>
}

DevLab_PostoAmigo/Views/Evento/Index.cshtml
@model DevLab_PostoAmigo.Models.EventModel
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper full-wide">
    <!-- Content Header (Page header) -->
    @*<section class="content-header">
            <h1>Data Tables</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="active"><i class="fa fa-envelope-o"></i> Tables</li>
                <li class="active"><i class="fa fa-table"></i> Data Tables</li>
            </ol>
        </section>*@

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="chart-box">
                    @using (Html.BeginForm("Filtrar", "Evento", FormMethod.Post))
                    {
                        <div class="row">
                            <div class="col-md-4">
                                <fieldset class="form-group">
                                    <label>IBM</label>
                                    @Html.TextBoxFor(x => x.Ibm, new { @class = "form-control", maxlength = 150 })
                                </fieldset>
                            </div>
                            <div class="col-md-4">
                                <fieldset class="form-group">
                                    <label>Status</label>
                                    @Html.DropDownList("IdStatus", (IEnumerable<SelectListItem>)ViewData["Menu"], "--", new { @class = "form-control" })
                                </fieldset>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <input type="submit" class="btn btn-info btn-rounded" value="Filtrar" />
                                <input type="button" class="btn btn-success btn-rounded" value="Export" id="Export" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="chart-box">
                    <table class="table table-responsive">
                        <thead>
                            <tr>
                                <th class="sortable">IBM</th>
                                <th class="sortable">Titulo</th>
                                <th class="sortable">Descrição</th>
                                <th>Data</th>
                                <th>Período</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        @foreach (var item in Model.ListEvent)
                        {
                            <tr>
                                <td class="text-truncate">@item.Ibm</td>
                                <td class="text-truncate">@item.Name</td>
                                <td class="text-truncate">@item.Description</td>
                                <td class="text-truncate">@item.DateEvent.ToString("dd/MM/yyyy")</td>
                                <td class="text-truncate">@item.HourStart - @item.HourEnd</td>

                                @if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusEvent.Approved)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-success">@item.NameStatus</span></td>
                                }
                                else if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusEvent.Disapproved)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-unpaid">@item.NameStatus</span></td>
                                }
                                else if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusEvent.Cancel)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-unpaid">@item.NameStatus</span></td>
                                }
                                else if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusEvent.Pending)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-warning">@item.NameStatus</span></td>
                                }
                                <td class="text-truncate"><a href="~/Evento/Details/@item.IdEvent">detalhes</a></td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!-- content -->
</div>
<!-- content-wrapper -->
@section scripts {
    <!-- Custom -->
    <script>
        $(function () {

            $('#Export').on('click', function (e) {

                var Ibm = $('#Ibm').val();
                var IdStatus = $('#IdStatus').val();

                window.location = '/Evento/Export?Ibm=' + Ibm + '&IdStatus=' + IdStatus;
            });

        });
    </script>
}