DevLab_PostoAmigo/Controllers/BeneficioController.cs
using DevLab_PostoAmigo.Business.Util;
using DevLab_PostoAmigo.Business.Return;
using DevLab_PostoAmigo.Business;
using DevLab_PostoAmigo.Data;
using DevLab_PostoAmigo.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.IO;

namespace DevLab_PostoAmigo.Controllers
{
    public class BeneficioController : Controller
    {
        [SessionCheck]
        public ActionResult Index()
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();
            ViewBag.IdType = new SelectList(Business.TypeBenefit.ListType().Select(x => new SelectListItem { Value = x.IdType.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");
            ViewBag.IdStatus = new SelectList(Business.StatusBenefit.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");

            var model = new Models.BenefitModel();
            model.ListBenefit = Business.Benfit.ListBenefit(null, null, null); 

            return View(model);
        }

        [SessionCheck]
        [HttpGet]
        public ActionResult Index(int? id)
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();
            ViewBag.IdType = new SelectList(Business.TypeBenefit.ListType().Select(x => new SelectListItem { Value = x.IdType.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");
            ViewBag.IdStatus = new SelectList(Business.StatusBenefit.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text", id.ToString());

            var model = new Models.BenefitModel();
            model.ListBenefit = Business.Benfit.ListBenefit(null, id, null);

            return View(model);
        }

        [SessionCheck]
        [HttpPost]
        public ActionResult Filtrar(Models.BenefitModel model)
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();
            ViewBag.IdType = new SelectList(Business.TypeBenefit.ListType().Select(x => new SelectListItem { Value = x.IdType.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");
            ViewBag.IdStatus = new SelectList(Business.StatusBenefit.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");

            model.ListBenefit = Business.Benfit.ListBenefit(model.Ibm, model.IdStatus, model.IdType);

            return View("Index", model);
        }

        [SessionCheck]
        [HttpGet]
        public ActionResult Export(long? Ibm, int? IdStatus, int? IdType)
        {

            ViewBag.IdType = new SelectList(Business.TypeBenefit.ListType().Select(x => new SelectListItem { Value = x.IdType.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");
            ViewBag.IdStatus = new SelectList(Business.StatusBenefit.ListStatus().Select(x => new SelectListItem { Value = x.IdStatus.ToString(), Text = x.Name }).OrderBy(o => o.Text).ToList(), "Value", "Text");

            var beneficios = Business.Benfit.ListBenefit(Ibm, IdStatus, IdType);
            // Create file
            DateTime now = TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("Central Brazilian Standard Time"));
            string filename = "Relatorio_Beneficios_" + now.ToString("ddMMyyyyHHmm") + ".xlsx";

            // Criar excel
            MemoryStream stream = new MemoryStream();
            ExcelStructure excel = new ExcelStructure("Beneficios", ref stream);

            excel.setColumnWidth(1, 20);  // Ibm
            excel.setColumnWidth(2, 20);  // NameStatus
            excel.setColumnWidth(3, 20);  // NameType
            excel.setColumnWidth(4, 30);  // Description
            excel.setColumnWidth(5, 20);  // Comments
            excel.setColumnWidth(6, 20);  // Quantity
            excel.setColumnWidth(7, 20);  // DateStart
            excel.setColumnWidth(8, 20);  // DateEnd
            excel.setColumnWidth(9, 20);  // Reason
            excel.setColumnWidth(10, 20); // DateCreate
            excel.setColumnWidth(11, 20); // DateUpdate

            excel.createSheetData();

            IList<string> headers = new List<string>();
            IList<string> valores = new List<string>();
            IList<int> tipos = new List<int>();

            headers = new List<string>();

            headers.Add("Ibm");
            headers.Add("Status");
            headers.Add("Tipo");
            headers.Add("Descrição");
            headers.Add("Observações");
            headers.Add("Quantidade");
            headers.Add("Data Inicio");
            headers.Add("Data Termino");
            headers.Add("Motivo");
            headers.Add("Data Criação");
            headers.Add("Data Atualização");

            excel.CreateColumnHeader(1, headers);

            uint row = 2;
            foreach (var c in beneficios)
            {
                valores = new List<string>();
                tipos = new List<int>();

                valores.Add(c.Ibm + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.NameStatus + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.NameType + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Description + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Comments + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Quantity + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.DateStart + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.DateEnd + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.Reason + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.DateCreate + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                valores.Add(c.DateUpdate + " ");
                tipos.Add(ExcelStructure.TYPE_STRING);

                excel.CreateRowWithContent(row, valores, tipos);
                row++;
            }

            excel.save();
            excel.close();

            stream.Position = 0;

            return new FileStreamResult(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            {
                FileDownloadName = filename
            };
        }

        [SessionCheck]
        public ActionResult Details(int id)
        {
            var user = Geral.RecuperaCookieAdmin();

            ViewBag.Name = user.Name.ToString();
            ViewBag.Email = user.Email.ToString();

            var statusBenefit = Business.StatusBenefit.ListStatus();
            var typeBenefit = Business.TypeBenefit.ListType();

            Benefit benefit = Business.Benfit.Details(id);
            Models.BenefitModel model = new Models.BenefitModel
            {
                IdBenefit = benefit.IdBenefit,
                Ibm = benefit.Ibm,
                IdStatus = benefit.IdStatus,
                IdType = benefit.IdType,
                Description = benefit.Description,
                Comments = benefit.Comments,
                Quantity = benefit.Quantity,
                DateStart = benefit.DateStart,
                DateEnd = benefit.DateEnd,
                Reason = benefit.Reason,
                DateCreate = benefit.DateCreate,
                DateUpdate = benefit.DateUpdate,
                NameStatus = benefit.NameStatus,
                NameType = benefit.NameType,
                ListStatusBenefit = statusBenefit,
                ListTypeBenefit = typeBenefit,
            };

            return View(model);
        }

        [SessionCheck]
        [HttpPost]
        public ActionResult Edit(string strDados)
        {
            Models.BenefitModel dados;

            try
            {
                dados = JsonConvert.DeserializeObject<Models.BenefitModel>(strDados);

                Business.Benfit.Edit(dados.IdBenefit, (int)dados.IdStatus, dados.Description, dados.Comments, dados.Reason);
            }
            catch
            {
                
            }

            return Json(true);
        }
    }
}

DevLab_PostoAmigo/Views/Beneficio/Details.cshtml
@model DevLab_PostoAmigo.Models.BenefitModel

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper full-wide">
    <!-- Content Header (Page header) -->
    @*<section class="content-header">
            <h1>Dashboard</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
            </ol>
        </section>*@

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="chart-box">
                    <div class="row">
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>IBM</label>
                                <input class="form-control" id="basicInput" type="text" value="@Model.Ibm" readonly="readonly">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Tipo de benefício</label>
                                <input class="form-control" id="basicInput" type="text" value="@Model.NameType" readonly="readonly">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Quantidade de benefícios disponiveis para a promoção</label>
                                <input class="form-control" id="basicInput" type="text" value="@Model.Quantity" readonly="readonly">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Data de início da promoção</label>
                                <input class="form-control" id="basicInput" type="text" value="@String.Format("{0:dd/MM/yyyy}", @Model.DateStart)" readonly="readonly">
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Data do término da promoção</label>
                                <input class="form-control" id="basicInput" type="text" value="@String.Format("{0:dd/MM/yyyy}", @Model.DateEnd)" readonly="readonly">
                            </fieldset>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Descrição do funcionamento da mecânica para a entrega do benefício</label>
                                <textarea class="form-control" id="txtDescription" rows="10">@Model.Description</textarea>
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Observações adicionais sobre o benefício a ser disponibilizado</label>
                                <textarea class="form-control" id="txtComments" rows="10">@Model.Comments</textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Status</label>
                                <select class="form-control" id="IdStatus">
                                    @foreach (var item in Model.ListStatusBenefit)
                                    {
                                        if (item.IdStatus == Model.IdStatus)
                                        {
                                            <option value="@item.IdStatus" selected>@item.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@item.IdStatus">@item.Name</option>
                                        }
                                    }
                                </select>
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group" id="dvReason">
                                <label>Motivo</label>
                                <textarea class="form-control" id="txtReason" rows="10">@Model.Reason</textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <input type="hidden" value="@Model.IdBenefit" id="IdBenefit" />
                            <a href="#" id="btnVoltar" class="btn btn-warning btn-rounded">Voltar</a>
                            <a href="#" id="btnSalvar" class="btn btn-info btn-rounded">Salvar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- content -->
</div>
<!-- content-wrapper -->
<!-- content-wrapper -->

@section scripts {
    <!-- Custom -->
    <script src="~/Scripts/dist/js/BenefitDetails.js"></script>
}

DevLab_PostoAmigo/Views/Beneficio/Index.cshtml
@model DevLab_PostoAmigo.Models.BenefitModel
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper full-wide">
    <!-- Content Header (Page header) -->
    @*<section class="content-header">
            <h1>Data Tables</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
                <li class="active"><i class="fa fa-envelope-o"></i> Tables</li>
                <li class="active"><i class="fa fa-table"></i> Data Tables</li>
            </ol>
        </section>*@

    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="chart-box">
                    <div class="row">
                        @using (Html.BeginForm("Filtrar", "Beneficio", FormMethod.Post))
                        {
                            <div class="col-md-4">
                                <fieldset class="form-group">
                                    <label>IBM</label>
                                    @Html.TextBoxFor(x => x.Ibm, new { @class = "form-control", maxlength = 150 })
                                </fieldset>
                            </div>
                            <div class="col-md-4">
                                <fieldset class="form-group">
                                    <label>Tipo</label>
                                    @Html.DropDownList("IdType", (IEnumerable<SelectListItem>)ViewData["Menu"], "--", new { @class = "form-control" })
                                </fieldset>
                            </div>
                            <div class="col-md-4">
                                <fieldset class="form-group">
                                    <label>Status</label>
                                    @Html.DropDownList("IdStatus", (IEnumerable<SelectListItem>)ViewData["Menu"], "--", new { @class = "form-control" })
                                </fieldset>
                            </div>
                            <div class="col-md-4">
                                <input type="submit" class="btn btn-info btn-rounded" value="Filtrar" />
                                <input type="button" class="btn btn-success btn-rounded" value="Export" id="Export" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="chart-box">
                    <table class="table table-responsive">
                        <thead>
                            <tr>
                                <th class="sortable">IBM</th>
                                <th class="sortable">Tipo</th>
                                <th class="sortable">Descrição</th>
                                <th class="sortable">Quantidade</th>
                                <th>Vigencia</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        @foreach (var item in Model.ListBenefit)
                        {
                            <tr>
                                <td class="text-truncate">@item.Ibm</td>
                                <td class="text-truncate">@item.NameType</td>
                                <td class="text-truncate">@item.Description</td>
                                <td class="text-truncate">@item.Quantity</td>

                                <td class="text-truncate">@String.Format("{0:dd/MM/yyyy}", item.DateStart) - @String.Format("{0:dd/MM/yyyy}", item.DateEnd)</td>

                                @if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusBenfit.Approved)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-success">@item.NameStatus</span></td>
                                }
                                else if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusBenfit.Disapproved)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-unpaid">@item.NameStatus</span></td>
                                }
                                else if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusBenfit.Cancel)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-unpaid">@item.NameStatus</span></td>
                                }
                                else if (@item.IdStatus == (int)DevLab_PostoAmigo.Business.Enum.StatusBenfit.Pending)
                                {
                                    <td class="text-truncate"><span class="lable-tag tag-warning">@item.NameStatus</span></td>
                                }

                                <td class="text-truncate"><a href="~/Beneficio/Details/@item.IdBenefit">detalhes</a></td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!-- content -->
</div>
<!-- content-wrapper -->
@section scripts {
    <!-- Custom -->
    <script>
        $(function () {

            $('#Export').on('click', function (e) {

                var Ibm = $('#Ibm').val();
                var IdType = $('#IdType').val();
                var IdStatus = $('#IdStatus').val();
                
                window.location = '/Beneficio/Export?Ibm=' + Ibm + '&IdStatus=' + IdStatus + '&IdType=' + IdType;
            });

        });
    </script>
}